### ISSUE TITLE
Cannot list EC2 instance

### ISSUE THREAD

**Issue by br-arruda** [welldone-cloud/aws-list-resources#7]
Hi, 

I just tried to use your script to discover ec2 instances, but got empty responses. I don't know if `--include-resource-types` is case sensitive (Is it?), so I tried both commands:

```bash
python aws_list_resources.py --regions us-east-1 --include-resource-types AWS::EC2::instance

python aws_list_resources.py --regions us-east-1 --include-resource-types AWS::EC2::Instance
```

The results were similar, in both commands:

```json
{
  "_metadata": {
    "account_id": "***",
    "account_principal": "arn:aws:iam::***:user/***",
    "denied_list_operations": {
      "us-east-1": []
    },
    "invocation": "aws_list_resources.py --regions us-east-1 --include-resource-types AWS::EC2::instance",
    "run_timestamp": "20240327125325"
  },
  "regions": {
    "us-east-1": {}
  }
}
```

**Comment by michael-kirchner-at** [comment]
Hi!

Thank you for reaching out! I looked into this and I believe you found a bug in AWS's CloudControl API (either in the implementation or in the documentation):

The following URL lists "AWS::EC2::Instance" as being supported, including the "List" operation: https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html

When I run the following CLI command though, I get back that this resource type is not yet supported:
```
aws cloudcontrol list-resources --type-name "AWS::EC2::Instance" --region eu-central-1

An error occurred (UnsupportedActionException) when calling the ListResources operation: The resource AWS::EC2::Instance is not yet supported via Cloud Control API
```

The error message is different though to a resource type that clearly does not exist:
```
aws cloudcontrol list-resources --type-name "AWS::EC2::XYZ" --region us-east-1

An error occurred (TypeNotFoundException) when calling the ListResources operation: The type 'AWS::EC2::XYZ' cannot be found.
```

So it seems to me that the CloudControl API recognizes "AWS::EC2::Instance", in principle, but the "List" implementation currently has an issue. Is it the same for you? If yes, I'd recommend contacting AWS about your finding.

Overall you are right that the script did not properly validate the values passed to the `--exclude-resource-types` and `--include-resource-types` parameters. I just pushed an update to the repo that enhances this. If you now run the script with a resource type that does not exist, you'll get a notification on the CLI and in the output file. For example:
```
aws_list_resources.py --region eu-central-1 --exclude-resource-type abc
```

Will lead to:
```
{
  "_metadata": {
    "account_id": "***",
    "account_principal": "***",
    "errors": {
      "eu-central-1": [
        "Provided resource type does not match any supported resource types in region eu-central-1: abc"
      ]
    },
    "invocation": "aws_list_resources.py --region eu-central-1 --exclude-resource-type abc",
    "run_timestamp": "20240327150359"
  }
  [...]
```

The CloudControl API, by the way, treats resources types in a case insensitive way. So both `AWS::EC2::Instance` and `AWS::EC2::instance` should be fine.

**Comment by michael-kirchner-at** [comment]
It seems that AWS has fixed this bug: The above-mentioned commands now do return EC2 instances present in the region. Thus closing this issue.
